export const textStyles = {
    h1: {
        fontFamily: "Inter",
        fontSize: "56px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "72px",
    },
    h2: {
        fontFamily: "Inter",
        fontSize: "48px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "64px",
    },
    h3: {
        fontFamily: "Inter",
        fontSize: "40px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "52px",
    },
    h4: {
        fontFamily: "Inter",
        fontSize: "32px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "40px",
    },
    h5: {
        fontFamily: "Inter",
        fontSize: "24px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "32px",
    },
    h6: {
        fontFamily: "Inter",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "24px",
    },
    b1: {
        fontFamily: "Inter",
        fontSize: "18px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "24px",
    },
    b2: {
        fontFamily: "Inter",
        fontSize: "16px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "20px",
    },
    b3: {
        fontFamily: "Inter",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "24px",
    },
    b4: {
        fontFamily: "Inter",
        fontSize: "12px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "16px",
    },
    b5: {
        fontFamily: "Inter",
        fontSize: "11px",
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: "14px",
    }
}