export enum TokenName {
    // global
    Identifier = "Identifier",
    Equals = "Equals",
    StringLiteral = "StringLiteral",
    NumericLiteral = "NumericLiteral",
    WhiteSpace = "WhiteSpace",
    LCurly = "LCurly",
    RCurly = "RCurly",
    Workspace = "Workspace",
    // model
    Model = "Model",
    Group = "Group",
    Person = "Person",
    SoftwareSystem = "SoftwareSystem",
    Container = "Container",
    Component = "Component",
    DeploymentEnvironment = "DeploymentEnvironment",
    DeploymentNode = "DeploymentNode",
    InfrastructureNode = "InfrastructureNode",
    RelationshipArrow = "RelationshipArrow",
    // element properties
    Name = "Name",
    Technology = "Technology",
    Description = "Description",
    Properties = "Properties",
    Perspectives = "Perspectives",
    Configuration = "Configuration",
    Tags = "Tags",
    Url = "Url",
    // views
    Views = "Views",
    SystemLandscape = "SystemLandscape",
    SystemContext = "SystemContext",
    Deployment = "Deployment",
    SoftwareSystemInstance = "SoftwareSystemInstance",
    ContainerInstance = "ContainerInstance",
    // views properties
    Include = "Include",
    Exclude = "Exclude",
    AutoLayout = "AutoLayout",
    Default = "Default",
    Animation = "Animation",
    Title = "Title",
    Themes = "Themes",
    // view style properties
    Styles = "Styles",
    Element = "Element",
    Relationship = "Relationship",
    Shape = "Shape",
    Icon = "Icon",
    Width = "Width",
    Height = "Height",
    Background = "Background",
    Color = "Color",
    StrokeWidth = "StrokeWidth",
    Stroke = "Stroke",
    Dashed = "Dashed",
    FontSize = "FontSize",
    Border = "Border",
    Opacity = "Opacity",
    Metadata = "Metadata",
    Thickness = "Thickness",
    Style = "Style",
    Routing = "Routing",
    Position = "Position",

    // view style property values
    HexColorLiteral = "HexColorLiteral",
    BooleanLiteral = "BooleanLiteral",
    UrlLiteral = "UrlLiteral",
    ThisLiteral = "This"
}