export enum ActionFlowType {
    CONNECT_PERSON_ON_SYSTEM_LANDSCAPE_VIEW = "CONNECT_PERSON_ON_SYSTEM_LANDSCAPE_VIEW",
    CONNECT_SOFTWARE_SYSTEM_ON_SYSTEM_LANDSCAPE_VIEW = "CONNECT_SOFTWARE_SYSTEM_ON_SYSTEM_LANDSCAPE_VIEW",
    CONNECT_PERSON_ON_SYSTEM_CONTEXT_VIEW = "CONNECT_PERSON_ON_SYSTEM_CONTEXT_VIEW",
    CONNECT_SOFTWARE_SYSTEM_ON_SYSTEM_CONTEXT_VIEW = "CONNECT_SOFTWARE_SYSTEM_ON_SYSTEM_CONTEXT_VIEW",
    CONNECT_PERSON_ON_CONTAINER_VIEW = "CONNECT_PERSON_ON_CONTAINER_VIEW",
    CONNECT_SOFTWARE_SYSTEM_ON_CONTAINER_VIEW = "CONNECT_SOFTWARE_SYSTEM_ON_CONTAINER_VIEW",
    CONNECT_CONTAINER_ON_CONTAINER_VIEW = "CONNECT_CONTAINER_ON_CONTAINER_VIEW",
    CONNECT_PERSON_ON_COMPONENT_VIEW = "CONNECT_PERSON_ON_COMPONENT_VIEW",
    CONNECT_SOFTWARE_SYSTEM_ON_COMPONENT_VIEW = "CONNECT_SOFTWARE_SYSTEM_ON_COMPONENT_VIEW",
    CONNECT_CONTAINER_ON_COMPONENT_VIEW = "CONNECT_CONTAINER_ON_COMPONENT_VIEW",
    CONNECT_COMPONENT_ON_COMPONENT_VIEW = "CONNECT_COMPONENT_ON_COMPONENT_VIEW",
}